# Copyright (C) 2025  Kendall Tauser
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

name: Build Containers
on:
  # push:
  #   branches:
  #     - "*"
  #   tags:
  #     - "*"
  # schedule:
  # - cron: "0 3 */21 * 0"
  workflow_dispatch:
    inputs:
      SKIP:
        description: Specify the list of images you want skip building, delimited '/'s.
        required: false
        default: ""
        type: string
      ONLY:
        description: Specify only one image to build. If specified, SKIP input is ignored.
        required: false
        default: ""
        type: string

jobs:
  debug:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'debug' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/debug/'))"
    with:
      APP_NAME: debug
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/debug/Dockerfile
      DOCKERFILE_CONTEXT: dockerfiles/debug/root

  direwolf:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'direwolf' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/direwolf/'))"
    with:
      APP_NAME: direwolf
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/direwolf/Dockerfile

  freeradius:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'freeradius' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/freeradius/'))"
    with:
      APP_NAME: freeradius
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/freeradius/Dockerfile

  grafana:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'grafana' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/grafana/'))"
    with:
      APP_NAME: grafana
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/grafana/Dockerfile

  openvpn:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'openvpn' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/openvpn/'))"
    with:
      APP_NAME: openvpn
      VERSION: v0.2.0
      DOCKERFILE_PATH: dockerfiles/openvpn/Dockerfile

  pdns-auth:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'pdns-auth' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/pdns-auth/'))"
    with:
      APP_NAME: pdns-auth
      VERSION: v0.3.0
      DOCKERFILE_PATH: dockerfiles/powerdns-auth/Dockerfile

  pdns-recursor:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'pdns-recursor' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/pdns-recursor/'))"
    with:
      APP_NAME: pdns-recursor
      VERSION: v0.2.0
      DOCKERFILE_PATH: dockerfiles/powerdns-recursor/Dockerfile

  soft-serve:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'soft-serve' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/soft-serve/'))"
    with:
      APP_NAME: soft-serve
      VERSION: v0.2.0
      DOCKERFILE_PATH: dockerfiles/soft-serve/Dockerfile

  terraria-server:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'terraria-server' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/terraria-server/'))"
    with:
      APP_NAME: terraria-server
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/terraria-server/Dockerfile

  tor:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'tor' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/tor/'))"
    with:
      APP_NAME: tor
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/tor/Dockerfile

  unbound-exporter:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'unbound-exporter' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/unbound-exporter/'))"
    with:
      APP_NAME: unbound-exporter
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/unbound-exporter/Dockerfile

  velocity:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'velocity' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/velocity/'))"
    with:
      APP_NAME: velocity
      VERSION: v0.2.0
      DOCKERFILE_PATH: dockerfiles/velocity/Dockerfile
      DOCKERFILE_CONTEXT: dockerfiles/velocity

  zeronsd:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'zeronsd' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/zeronsd/'))"
    with:
      APP_NAME: zeronsd
      VERSION: v0.1.0
      DOCKERFILE_PATH: dockerfiles/zeronsd/Dockerfile

  zerotier:
    uses: fire833/cicd-templates/.github/workflows/containers_cd_v1.yaml@main
    if: "inputs.ONLY == 'zerotier' || (inputs.ONLY == '' && !contains(inputs.SKIP, '/zerotier/'))"
    with:
      APP_NAME: zerotier
      VERSION: v0.2.1
      DOCKERFILE_PATH: dockerfiles/zerotier/Dockerfile
